# Generated by Django 5.1.3 on 2024-12-19 05:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_date_transaction_notes'),
        ('purchases', '0001_initial'),
        ('sales', '0004_customer_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('Card', 'شبكة')], max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('Card', 'شبكة')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
