# Generated by Django 5.1.3 on 2024-12-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_trial_active_profile_trial_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trial_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trial_start_date',
        ),
    ]
