# Generated by Django 5.1.3 on 2024-12-07 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_printer_alter_category_name_fk_and_more'),
        ('printsettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='printer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='printsettings.printer', verbose_name='الطابعة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fk',
            field=models.CharField(max_length=255, verbose_name='اسم القسم E'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_lo',
            field=models.CharField(max_length=255, verbose_name='اسم القسم ع'),
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
