# Generated by Django 5.1.3 on 2025-01-05 00:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('id_card_number', models.CharField(max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('hiring_date', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_status', models.CharField(choices=[('active', 'على رأس العمل'), ('inactive', 'موقف عن العمل')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accruals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accrual_date', models.DateField(default=datetime.date.today)),
                ('deduction_date', models.DateField(default=datetime.date.today)),
                ('accrual_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('deduction_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('paid', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
