# Generated by Django 5.1.3 on 2025-01-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='supplier_balance',
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('نقدي', 'نقدي'), ('بطاقة', 'بطاقة')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('نقدي', 'نقدي'), ('بطاقة', 'بطاقة')], max_length=50),
        ),
    ]
