# Generated by Django 5.1.3 on 2025-01-05 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxApp', '0001_initial'),
        ('configrate', '0001_initial'),
        ('input', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoicelocal',
            fields=[
                ('purchaseinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchases.purchaseinvoice')),
            ],
            options={
                'verbose_name': 'فاتورة مشتريات محلية',
                'db_table': 'purchase_invoicelocal',
            },
            bases=('purchases.purchaseinvoice',),
        ),
        migrations.RemoveField(
            model_name='purchaseinvoicedetail',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoicedetail',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.store'),
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='tax',
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name': 'فاتورة مشتريات'},
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='total_tax',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tax_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TaxApp.tax'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount_type',
            field=models.CharField(choices=[('amount', 'خصم بالسعر'), ('percentage', 'خصم بالنسبة المئوية')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'شبكة')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='purchaseinvoice',
            table='purchase_invoice',
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.items')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchases.purchaseinvoice')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configrate.unit')),
            ],
            options={
                'verbose_name': 'تفاصيل الفاتورة',
                'db_table': 'invoice_detail',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoiceDetail',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
