# Generated by Django 5.1.3 on 2024-12-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configrate', '0002_programsettings'),
        ('purchases', '0002_remove_purchaseinvoicelocaldetails_purchase_invoicelocal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم عربي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
                ('is_stop', models.BooleanField(default=True, verbose_name='مغلق')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configrate.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
