# Generated by Django 5.1.3 on 2024-12-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_store_remove_invoice_warehouse_invoice_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('network', 'شبكة')], default='cash', max_length=10),
        ),
    ]
