# Generated by Django 5.1.3 on 2024-12-22 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_invoicecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
