# Generated by Django 5.1.3 on 2024-12-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_invoice_supplier_invoice_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
