# Generated by Django 5.1.3 on 2025-01-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='إسم الشركة')),
                ('tax_number', models.CharField(max_length=20, verbose_name='الرقم الضريبي')),
                ('email', models.EmailField(max_length=254, verbose_name='الإيميل')),
                ('commercial', models.CharField(max_length=20, verbose_name='السجل التجاري')),
                ('state', models.CharField(max_length=50, verbose_name='الدولة')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('telephone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='رقم الجوال')),
                ('note', models.TextField(verbose_name='ملاحظات')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='الشعار')),
            ],
        ),
    ]
