# Generated by Django 5.1.3 on 2024-12-15 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'الضريبة', 'verbose_name_plural': 'الضرائب'},
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الضريبة'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الضريبة'),
        ),
    ]
