# Generated by Django 5.1.3 on 2024-12-07 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configrate', '0001_initial'),
        ('input', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الإنشاء')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('name_lo', models.CharField(max_length=100, verbose_name='إسم العميل ع')),
                ('name_fk', models.CharField(max_length=100, verbose_name='E إسم العميل')),
                ('VatNumber', models.CharField(max_length=50, verbose_name='الرقم الضريبي')),
                ('Telphone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الجوال')),
                ('Address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('is_stop', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoicelocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الإنشاء')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_stage', models.BooleanField(default=False, verbose_name='هل هو مرحلة؟')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='هل هو موقوف؟')),
                ('tax', models.FloatField(blank=True, null=True, verbose_name='الضريبة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('check_amount', models.FloatField(blank=True, null=True, verbose_name='قيمة الشيك')),
                ('stop', models.BooleanField(default=False, verbose_name='إيقاف')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='إجمالي الفاتورة المحلية')),
                ('statement', models.CharField(max_length=100, verbose_name='بيان')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('total_amount', models.FloatField(verbose_name='إجمالي المبلغ')),
                ('discount', models.FloatField(default=0, verbose_name='الخصم')),
                ('discount_rate', models.FloatField(blank=True, null=True, verbose_name='معدل الخصم %')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('credit_card', 'شبكة ')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='العميل')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فاتورة مبيعات محلية',
                'db_table': 'Sales_invoicelocal',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoicelocalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الإنشاء')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('qty', models.PositiveIntegerField(verbose_name='الكمية')),
                ('free_qty', models.PositiveIntegerField(default=0, verbose_name='الكمية المجانية')),
                ('statement', models.CharField(blank=True, max_length=100, null=True, verbose_name='بيان')),
                ('discount', models.FloatField(blank=True, default=0, null=True, verbose_name='الخصم')),
                ('discount_rate', models.FloatField(blank=True, null=True, verbose_name='معدل الخصم %')),
                ('selling_price', models.FloatField(blank=True, null=True, verbose_name='سعر البيع')),
                ('Sales_invoicelocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesinvoicelocal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='input.items')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configrate.store')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configrate.unit')),
            ],
            options={
                'verbose_name': 'تفاصيل فاتورة مبيعات محلية',
                'db_table': 'Sales_invoicelocal_details',
            },
        ),
    ]
