# Generated by Django 5.1.3 on 2024-12-18 12:45

import datetime
from django.utils import timezone
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),  # تغيير القيمة الافتراضية
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.CharField(default="", max_length=255),  # تغيير القيمة الافتراضية
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Telphone',
            field=models.CharField(default="", max_length=50),  # تغيير القيمة الافتراضية
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='VatNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_fk',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_lo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default="", max_length=50),  # تغيير القيمة الافتراضية
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الإنشاء')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('amount', models.FloatField(verbose_name='المبلغ')),
                ('transaction_type', models.CharField(choices=[('credit', 'دائن'), ('debit', 'مدين')], default='debit', max_length=10)),
                ('transaction_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ المعاملة')),
                ('statement', models.CharField(blank=True, max_length=255, null=True, verbose_name='البيان')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer', verbose_name='العميل')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
