# Generated by Django 5.1.3 on 2024-12-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created',
        ),
    ]
