# Generated by Django 5.1.3 on 2024-12-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customer_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name_fk',
        ),
    ]
